output_step_rod_05_1 = load("..\..\data\system_id_data\id_result_step_rod_05_1.mat");
output_step_rod_05_1 = output_step_rod_05_1.output;
output_step_rod_06_1 = load("..\..\data\system_id_data\id_result_step_rod_06_1.mat");
output_step_rod_06_1 = output_step_rod_06_1.output;
output_step_rod_07_1 = load("..\..\data\system_id_data\id_result_step_rod_07_1.mat");
output_step_rod_07_1 = output_step_rod_07_1.output;
output_step_rod_03_1 = load("..\..\data\system_id_data\id_result_step_rod_03_1.mat");
output_step_rod_03_1 = output_step_rod_03_1.output;
output_step_rod_04_1 = load("..\..\data\system_id_data\id_result_step_rod_04_1.mat");
output_step_rod_04_1 = output_step_rod_04_1.output;

output_chirp_rod_05_01_10_1 = load("..\..\data\system_id_data\id_result_chirp_rod_05_01_10_1.mat");
output_chirp_rod_05_01_10_1 = output_chirp_rod_05_01_10_1.output;
output_chirp_rod_05_10_100_1 = load("..\..\data\system_id_data\id_result_chirp_rod_05_10_100_1.mat");
output_chirp_rod_05_10_100_1 = output_chirp_rod_05_10_100_1.output;
output_chirp_rod_05_0001_01_1 = load("..\..\data\system_id_data\id_result_chirp_rod_05_0001_01_1.mat");
output_chirp_rod_05_0001_01_1 = output_chirp_rod_05_0001_01_1.output;
%%
figure; hold on; grid on
freq_list = [0.3 0.4 0.5 0.6 0.7];
plot(freq_list,...
    [output_step_rod_03_1.tau_pos; ...
    output_step_rod_04_1.tau_pos; ...
    output_step_rod_05_1.tau_pos; ...
    output_step_rod_06_1.tau_pos; ...
    output_step_rod_07_1.tau_pos], '.', 'MarkerSize', 30)

plot(freq_list,...
    [output_step_rod_03_1.tau_pos_fit; ...
    output_step_rod_04_1.tau_pos_fit; ...
    output_step_rod_05_1.tau_pos_fit; ...
    output_step_rod_06_1.tau_pos_fit; ...
    output_step_rod_07_1.tau_pos_fit], '.', 'MarkerSize', 30)
plot(freq_list,...
    [output_step_rod_03_1.tau_vel; ...
    output_step_rod_04_1.tau_vel; ...
    output_step_rod_05_1.tau_vel; ...
    output_step_rod_06_1.tau_vel; ...
    output_step_rod_07_1.tau_vel], '.', 'MarkerSize', 30)
plot(freq_list,...
    [output_step_rod_03_1.tau_vel; ...
    output_step_rod_04_1.tau_vel_fit; ...
    output_step_rod_05_1.tau_vel_fit; ...
    output_step_rod_06_1.tau_vel_fit; ...
    output_step_rod_07_1.tau_vel_fit], '.', 'MarkerSize', 30)

plot([0.5 0.5], [output_chirp_rod_05_0001_01_1.tau_vel, ...
    output_chirp_rod_05_01_10_1.tau_vel], '.', 'MarkerSize', 30)

legend("Position Direct", ...
    "Position Fit", ...
    "Velocity Direct", ...
    "Velocity Fit")
%%
figure; hold on; grid on
freq_list = [0.3 0.4 0.5 0.6 0.7];
plot(freq_list,...
    [output_step_rod_03_1.kapa_pos; ...
    output_step_rod_04_1.kapa_pos; ...
    output_step_rod_05_1.kapa_pos; ...
    output_step_rod_06_1.kapa_pos; ...
    output_step_rod_07_1.kapa_pos], '.', 'MarkerSize', 30)

plot(freq_list,...
    [output_step_rod_03_1.kapa_pos_fit; ...
    output_step_rod_04_1.kapa_pos_fit; ...
    output_step_rod_05_1.kapa_pos_fit; ...
    output_step_rod_06_1.kapa_pos_fit; ...
    output_step_rod_07_1.kapa_pos_fit], '.', 'MarkerSize', 30)
plot(freq_list,...
    [output_step_rod_03_1.kapa_vel; ...
    output_step_rod_04_1.kapa_vel; ...
    output_step_rod_05_1.kapa_vel; ...
    output_step_rod_06_1.kapa_vel; ...
    output_step_rod_07_1.kapa_vel], '.', 'MarkerSize', 30)
plot(freq_list,...
    [output_step_rod_03_1.kapa_vel; ...
    output_step_rod_04_1.kapa_vel_fit; ...
    output_step_rod_05_1.kapa_vel_fit; ...
    output_step_rod_06_1.kapa_vel_fit; ...
    output_step_rod_07_1.kapa_vel_fit], '.', 'MarkerSize', 30)
plot([0.5 0.5], [output_chirp_rod_05_0001_01_1.kapa_vel, ...
    output_chirp_rod_05_01_10_1.kapa_vel], '.', 'MarkerSize', 30)

legend("Position Direct", ...
    "Position Fit", ...
    "Velocity Direct", ...
    "Velocity Fit", ...
    "Chirp")
%%
kapa_model = mean([output_step_rod_03_1.kapa_vel; ...
    output_step_rod_04_1.kapa_vel_fit; ...
    output_step_rod_05_1.kapa_vel_fit; ...
    output_step_rod_06_1.kapa_vel_fit; ...
    output_step_rod_07_1.kapa_vel_fit])

tau_model = mean([output_step_rod_03_1.tau_vel; ...
    output_step_rod_04_1.tau_vel_fit; ...
    output_step_rod_05_1.tau_vel_fit; ...
    output_step_rod_06_1.tau_vel_fit; ...
    output_step_rod_07_1.tau_vel_fit])
%%
sys_model = tf(kapa_model, [tau_model 1])
figure; hold on; grid on
my_bode = bodeplot(sys_model);

bodeplot(output_chirp_rod_05_0001_01_1.chirp_sys, {0.025*2*pi 0.23*2*pi})
bodeplot(output_chirp_rod_05_01_10_1.chirp_sys, {0.23*2*pi 9.03*2*pi})
bodeplot(output_chirp_rod_05_10_100_1.chirp_sys, {9.03*2*pi 100*2*pi});
setoptions(my_bode,'FreqUnits','Hz', 'Xlim', [0.025 100], 'Grid', 'on');
legend("System of Our Model", "Plant Low Frequency Response", ...
    "Plant Mid Frequency Response", "Plant High Frequency Response")

Fh = gcf;                                                   % Handle To Current Figure
Kids = Fh.Children;                                         % Children
AxAll = findobj(Kids,'Type','Axes');                        % Handles To Axes
Ax1 = AxAll(1);                                             % First Set Of Axes
LinesAx1 = findobj(Ax1,'Type','Line');                      % Handle To Lines
LinesAx1(2).LineWidth = 2;
LinesAx1(3).LineWidth = 2;   
LinesAx1(4).LineWidth = 2;                                  % Set ‘LineWidth’
Ax2 = AxAll(2);                                             % Second Set Of Axes
LinesAx2 = findobj(Ax2,'Type','Line');                      % Handle To Lines
LinesAx2(2).LineWidth = 2;                                  % Set ‘LineWidth’
LinesAx2(3).LineWidth = 2;    
LinesAx2(4).LineWidth = 2;    